export const csvData = `alias,name,venue,room,categories,sortOrder,timeStart,timeEnd,contributors,descriptionHtml
application-insights-data-lake-and-power-bi,"Application Insights, Data Lake & Power BI",templafy-aps,Room 6,"Productivity & Library, Library Admin",100,2019-08-07 12:45,2019-08-07 14:00,maren-demuth,"<div>Show tracking in Application Insights, and how data flows to Data Lake and Power BI. Ensure everyone understands that tracking is a part of every story. <br /><strong>Hands-on:</strong> Query PowerBI &amp; Applicaiton Insights</div>"
application-insights-data-lake-and-power-bi-2,"Application Insights, Data Lake & Power BI",templafy-aps,Room 2,"Dynamics, Integrations",100,2019-08-07 14:15,2019-08-07 15:30,maren-demuth,"<div>Show tracking in Application Insights, and how data flows to Data Lake and Power BI. Ensure everyone understands that tracking is a part of every story. <br /><strong>Hands-on:</strong> Query PowerBI &amp; Applicaiton Insights</div>"
application-insights-data-lake-and-power-bi-3,"Application Insights, Data Lake & Power BI",templafy-aps,Room 2,"Platform, Email Signature",100,2019-08-07 15:45,2019-08-07 17:00,maren-demuth,"<div>Show tracking in Application Insights, and how data flows to Data Lake and Power BI. Ensure everyone understands that tracking is a part of every story. <br /><strong>Hands-on:</strong> Query PowerBI &amp; Applicaiton Insights</div>"
clean-code-backend-and-coding-convention-in-templafy,Clean code (Backend) and coding convention in Templafy,templafy-aps,Room 5,"Productivity & Library, Library Admin",100,2019-08-07 09:00,2019-08-07 10:15,rene-gundersen,"<div>Explain what we consider clean code. Introduce SonarQube, R# Analytics &amp; Code Cleanup, and time saving shortcuts.<br /><strong>Hands on:</strong> Clean up a piece of not so clean code (without using the mouse!)</div>"
clean-code-backend-and-coding-convention-in-templafy-2,Clean code (Backend) and coding convention in Templafy,templafy-aps,Room 5,"Dynamics, Integrations",100,2019-08-07 10:30,2019-08-07 11:45,rene-gundersen,"<div>Explain what we consider clean code. Introduce SonarQube, R# Analytics &amp; Code Cleanup, and time saving shortcuts.<br /><strong>Hands on:</strong> Clean up a piece of not so clean code (without using the mouse!)</div>"
clean-code-backend-and-coding-convention-in-templafy-3,Clean code (Backend) and coding convention in Templafy,templafy-aps,Room 5,"Platform, Email Signature",100,2019-08-07 12:45,2019-08-07 14:00,rene-gundersen,"<div>Explain what we consider clean code. Introduce SonarQube, R# Analytics &amp; Code Cleanup, and time saving shortcuts.<br /><strong>Hands on:</strong> Clean up a piece of not so clean code (without using the mouse!)</div>"
database-and-code-migrations,Database and code migrations,templafy-aps,Room 5,"Productivity & Library, Library Admin",100,2019-08-08 12:45,2019-08-08 14:00,ashkan-sirous,"<div>Ensure that everyone understands our Cloud stack. Including Application Gateway, Traffic Manager, Azure Functions, Service Bus, Key Vault, Docker in Web Apps, Elastic Pool, TerraForm, Security Center</div>"
database-and-code-migrations-2,Database and code migrations,templafy-aps,Room 5,"Dynamics, Integrations",100,2019-08-08 14:15,2019-08-08 15:30,ashkan-sirous,"<div>Ensure that everyone understands our Cloud stack. Including Application Gateway, Traffic Manager, Azure Functions, Service Bus, Key Vault, Docker in Web Apps, Elastic Pool, TerraForm, Security Center</div>"
database-and-code-migrations-3,Database and code migrations,templafy-aps,Room 5,"Platform, Email Signature",100,2019-08-08 15:45,2019-08-08 17:00,ashkan-sirous,"<div>Ensure that everyone understands our Cloud stack. Including Application Gateway, Traffic Manager, Azure Functions, Service Bus, Key Vault, Docker in Web Apps, Elastic Pool, TerraForm, Security Center</div>"
dinner,Dinner,undici,,Social,100,2019-08-06 19:00,,,
dinner-2,Dinner,kayak-bar,,Social,100,2019-08-07 18:30,,,
docker,Docker,templafy-aps,Room 1,"Platform, Email Signature",100,2019-08-06 12:45,2019-08-06 14:00,morten-henriksen,"<div>Ensure everyone is familiar with Docker, Docker-compose, Enviroment varibles, docker pull/build/up/down, etc. Nginx<br /><strong>Hands-on:</strong> Spinup a Self-contained systems, Change to another, add a new dependency to a new system</div>"
docker-2,Docker,templafy-aps,Room 1,"Productivity & Library, Library Admin",100,2019-08-06 14:15,2019-08-06 15:30,morten-henriksen,"<div>Ensure everyone is familiar with Docker, Docker-compose, Enviroment varibles, docker pull/build/up/down, etc. Nginx<br /><strong>Hands-on:</strong> Spinup a Self-contained systems, Change to another, add a new dependency to a new system</div>"
docker-3,Docker,templafy-aps,Room 1,"Dynamics, Integrations",100,2019-08-06 15:45,2019-08-06 17:00,morten-henriksen,"<div>Ensure everyone is familiar with Docker, Docker-compose, Enviroment varibles, docker pull/build/up/down, etc. Nginx<br /><strong>Hands-on:</strong> Spinup a Self-contained systems, Change to another, add a new dependency to a new system</div>"
domain-driven-design,Domain Driven Design,templafy-aps,Room 5,"Productivity & Library, Library Admin",100,2019-08-06 12:45,2019-08-06 14:00,lars-thomsen,"<div>Explain Bounded Context, Ubigtious Language, and patterns like Layered Archicture, Repository, Services, Domain Events, Specefications, Aggregate, Entity and Value objects.<br /><strong>Hands-on:</strong> Create a Repository, Service Query, Command and rais events.</div>"
domain-driven-design-2,Domain Driven Design,templafy-aps,Room 2,"Dynamics, Integrations",100,2019-08-06 14:15,2019-08-06 15:30,lars-thomsen,"<div>Explain Bounded Context, Ubigtious Language, and patterns like Layered Archicture, Repository, Services, Domain Events, Specefications, Aggregate, Entity and Value objects.<br /><strong>Hands-on:</strong> Create a Repository, Service Query, Command and rais events.</div>"
domain-driven-design-3,Domain Driven Design,templafy-aps,Room 2,"Platform, Email Signature",100,2019-08-06 15:45,2019-08-06 17:00,lars-thomsen,"<div>Explain Bounded Context, Ubigtious Language, and patterns like Layered Archicture, Repository, Services, Domain Events, Specefications, Aggregate, Entity and Value objects.<br /><strong>Hands-on:</strong> Create a Repository, Service Query, Command and rais events.</div>"
event-driven-archicture,Event Driven Archicture,templafy-aps,Room 1,"Productivity & Library, Library Admin",100,2019-08-08 09:00,2019-08-08 10:15,,"<div>Explain how events let data flow between Self-contained Systems. Show how we gurantee that events are delivered, and how the systems eventually will be consistent.<br /><strong>Hand-on:</strong> Raise events in one system and receive in another</div>"
event-driven-archicture-2,Event Driven Archicture,templafy-aps,Room 6,"Dynamics, Integrations",100,2019-08-08 10:30,2019-08-08 11:45,,"<div>Explain how events let data flow between Self-contained Systems. Show how we gurantee that events are delivered, and how the systems eventually will be consistent.<br /><strong>Hand-on:</strong> Raise events in one system and receive in another</div>"
event-driven-archicture-3,Event Driven Archicture,templafy-aps,Room 6,"Platform, Email Signature",100,2019-08-08 12:45,2019-08-08 14:00,,"<div>Explain how events let data flow between Self-contained Systems. Show how we gurantee that events are delivered, and how the systems eventually will be consistent.<br /><strong>Hand-on:</strong> Raise events in one system and receive in another</div>"
infrastructure-as-code-with-terraform,Infrastructure as Code with Terraform,templafy-aps,Room 1,"Productivity & Library, Library Admin",100,2019-08-08 14:15,2019-08-08 15:30,"attila-kurucz, bo-larsen","<div>Explain how all changes to Feature and Production environments will be done as code with version control, using Terraform<br /><strong>Hands-on:</strong> Everyone will provisioning a new service and afterwards upgrade, and finally delete it</div>"
infrastructure-as-code-with-terraform-2,Infrastructure as Code with Terraform,templafy-aps,Room 2,"Dynamics, Integrations",100,2019-08-08 15:45,2019-08-08 17:00,"attila-kurucz, bo-larsen","<div>Explain how all changes to Feature and Production environments will be done as code with version control, using Terraform<br /><strong>Hands-on:</strong> Everyone will provisioning a new service and afterwards upgrade, and finally delete it</div>"
infrastructure-as-code-with-terraform-3,Infrastructure as Code with Terraform,templafy-aps,Room 2,"Platform, Email Signature",100,2019-08-08 09:00,2019-08-08 10:15,"attila-kurucz, bo-larsen","<div>Explain how all changes to Feature and Production environments will be done as code with version control, using Terraform<br /><strong>Hands-on:</strong> Everyone will provisioning a new service and afterwards upgrade, and finally delete it</div>"
keynote-collaboration-and-agile-principles,Keynote: Collaboration and Agile principles,templafy-aps,Room 4 + 5 + 6,"Productivity & Library, Library Admin, Dynamics, Integrations, Platform, Email Signature",100,2019-08-06 09:00,2019-08-06 10:15,thomas-jespersen,"<div>We will talk about Team structure (Squads, Guilds, etc). We will talk about who is responsible for our technical platform, and why colaboration and sharing across teams is key to success.</div>"
meet-your-team-and-product-owner-team-1,Meet your Team and Product Owner (Library Admin Team),templafy-aps,Room 1,"Productivity & Library, Library Admin",100,2019-08-06 17:15,2019-08-06 18:00,,"<div>Your Product Owner will introduce the Team Road map, and you will discuss how the first sprints should run.</div>"
meet-your-team-and-product-owner-team-2,Meet your Team and Product Owner (Productivity & Library Team),templafy-aps,Room 1,"Productivity & Library, Library Admin",100,2019-08-07 17:15,2019-08-07 18:00,,"<div>Your Product Owner will introduce the Team Road map, and you will discuss how the first sprints should run.</div>"
meet-your-team-and-product-owner-team-3,Meet your Team and Product Owner (Integrations Team),templafy-aps,Room 2,"Dynamics, Integrations",100,2019-08-06 17:15,2019-08-06 18:00,,"<div>Your Product Owner will introduce the Team Road map, and you will discuss how the first sprints should run.</div>"
meet-your-team-and-product-owner-team-4,Meet your Team and Product Owner (Dynamics team),templafy-aps,Room 2,"Dynamics, Integrations",100,2019-08-08 17:15,2019-08-08 18:00,,"<div>Your Product Owner will introduce the Team Road map, and you will discuss how the first sprints should run.</div>"
meet-your-team-and-product-owner-team-5,Meet your Team and Product Owner (Platform Team),templafy-aps,Room 5,"Platform, Email Signature",100,2019-08-06 17:15,2019-08-06 18:00,,"<div>Your Product Owner will introduce the Team Road map, and you will discuss how the first sprints should run.</div>"
meet-your-team-and-product-owner-team-6,Meet your Team and Product Owner (Email Signature Team),templafy-aps,Room 5,"Platform, Email Signature",100,2019-08-07 17:15,2019-08-07 18:00,,"<div>Your Product Owner will introduce the Team Road map, and you will discuss how the first sprints should run.</div>"
release-procedure-and-monitoring,Release Procedure and monitoring,templafy-aps,Room 2,"Productivity & Library, Library Admin",100,2019-08-08 10:30,2019-08-08 11:45,dan-antal,"<div>Show how our release procedure works. Including pair reviews. Introduce git and trunked based development, Azure Pipelines. Introduce code and database migragions. Show PagerDuty and StatusPage:Azure DevOps automation.<br /><strong>Hands-on:</strong> Setup a build pipe line in yaml</div>"
release-procedure-and-monitoring-2,Release Procedure and monitoring,templafy-aps,Room 2,"Dynamics, Integrations",100,2019-08-08 12:45,2019-08-08 14:00,dan-antal,"<div>Show how our release procedure works. Including pair reviews. Introduce git and trunked based development, Azure Pipelines. Introduce code and database migragions. Show PagerDuty and StatusPage:Azure DevOps automation.<br /><strong>Hands-on:</strong> Setup a build pipe line in yaml</div>"
release-procedure-and-monitoring-3,Release Procedure and monitoring,templafy-aps,Room 2,"Platform, Email Signature",100,2019-08-08 14:15,2019-08-08 15:30,dan-antal,"<div>Show how our release procedure works. Including pair reviews. Introduce git and trunked based development, Azure Pipelines. Introduce code and database migragions. Show PagerDuty and StatusPage:Azure DevOps automation.<br /><strong>Hands-on:</strong> Setup a build pipe line in yaml</div>"
scavenger-hunt,Scavenger hunt,templafy-aps,,Social,100,2019-08-06 18:00,2019-08-06 19:00,,
security-awareness-and-ethical-hacking,Security awareness and ethical hacking,templafy-aps,Room 6,"Productivity & Library, Library Admin",100,2019-08-08 15:45,2019-08-08 17:00,christian-peeters,<div>TBA</div>
security-awareness-and-ethical-hacking-2,Security awareness and ethical hacking,templafy-aps,Room 5,"Dynamics, Integrations",100,2019-08-08 09:00,2019-08-08 10:15,christian-peeters,<div>TBA</div>
security-awareness-and-ethical-hacking-3,Security awareness and ethical hacking,templafy-aps,Room 5,"Platform, Email Signature",100,2019-08-08 10:30,2019-08-08 11:45,christian-peeters,<div>TBA</div>
self-contained-systems,Self-contained systems,templafy-aps,Room 4 + 5 + 6,"Productivity & Library, Library Admin, Dynamics, Integrations, Platform, Email Signature",100,2019-08-06 10:30,2019-08-06 11:45,thomas-jespersen,"<div>Explain the overall structure of Self-contained systems, and how the differ from Micro services. Explain the flow of data and over all archictecture of the future Templafy.</div>"
teamwork-in-templafy,Teamwork in Templafy,templafy-aps,Room 1,"Productivity & Library, Library Admin",100,2019-08-07 15:45,2019-08-07 17:00,mie-aoki,"<div>Mie will talk about team dynamics and the phases new teams go through. She will (hopefully) make some small team exercises, which you can use to build trust.</div>"
teamwork-in-templafy-2,Teamwork in Templafy,templafy-aps,Room 1,"Dynamics, Integrations",100,2019-08-07 09:00,2019-08-07 10:15,mie-aoki,"<div>Mie will talk about team dynamics and the phases new teams go through. She will (hopefully) make some small team exercises, which you can use to build trust.</div>"
teamwork-in-templafy-3,Teamwork in Templafy,templafy-aps,Room 1,"Platform, Email Signature",100,2019-08-07 10:30,2019-08-07 11:45,mie-aoki,"<div>Mie will talk about team dynamics and the phases new teams go through. She will (hopefully) make some small team exercises, which you can use to build trust.</div>"
ui-tests-with-cypress,UI Tests with Cypress,templafy-aps,Room 6,"Productivity & Library, Library Admin",100,2019-08-07 10:30,2019-08-07 11:45,"jakob-hansen, ioana-galan",<div>Show how Cypress will make end-to-end test fast and stable. Every developer must be able to write these tests as they must be done before we release.<br /><strong>Hands-on:</strong> Create a new test and reuse existing steps</div>
ui-tests-with-cypress-2,UI Tests with Cypress,templafy-aps,Room 1,"Dynamics, Integrations",100,2019-08-07 12:45,2019-08-07 14:00,"jakob-hansen, ioana-galan",<div>Show how Cypress will make end-to-end test fast and stable. Every developer must be able to write these tests as they must be done before we release.<br /><strong>Hands-on:</strong> Create a new test and reuse existing steps</div>
ui-tests-with-cypress-3,UI Tests with Cypress,templafy-aps,Room 5,"Platform, Email Signature",100,2019-08-07 14:15,2019-08-07 15:30,"jakob-hansen, ioana-galan",<div>Show how Cypress will make end-to-end test fast and stable. Every developer must be able to write these tests as they must be done before we release.<br /><strong>Hands-on:</strong> Create a new test and reuse existing steps</div>
unit-tests,Unit Tests,templafy-aps,Room 6,"Dynamics, Integrations",100,2019-08-06 12:45,2019-08-06 14:00,matthias-mayrock,"<div>See how we write greate Tests in our Self-contained systems. We focus on behaviour and not implementation. This session wil introduce Nsubstitute for mocking, and EF inmemory database for fast database testing.<br /><strong>Hands-on:</strong> Write a couple of tests using mocking</div>"
unit-tests-2,Unit Tests,templafy-aps,Room 5,"Platform, Email Signature",100,2019-08-06 14:15,2019-08-06 15:30,matthias-mayrock,"<div>See how we write greate Tests in our Self-contained systems. We focus on behaviour and not implementation. This session wil introduce Nsubstitute for mocking, and EF inmemory database for fast database testing.<br /><strong>Hands-on:</strong> Write a couple of tests using mocking</div>"
unit-tests-3,Unit Tests,templafy-aps,Room 5,"Productivity & Library, Library Admin",100,2019-08-06 15:45,2019-08-06 17:00,matthias-mayrock,"<div>See how we write greate Tests in our Self-contained systems. We focus on behaviour and not implementation. This session wil introduce Nsubstitute for mocking, and EF inmemory database for fast database testing.<br /><strong>Hands-on:</strong> Write a couple of tests using mocking</div>"
using-ui-toolkit-and-frontend-development,Using UI Toolkit and frontend development,templafy-aps,Room 1,"Productivity & Library, Library Admin",100,2019-08-07 14:15,2019-08-07 15:30,"dan-antal, morten-henriksen","<div>Show how the UI can build, almost without styling. So coding convention and clean code. Ensure everyone uderstands snapshot testing.<br /><strong>Hands-on:</strong> Create a simple form like Invite User</div>"
using-ui-toolkit-and-frontend-development-2,Using UI Toolkit and frontend development,templafy-aps,Room 5,"Dynamics, Integrations",100,2019-08-07 15:45,2019-08-07 17:00,"dan-antal, morten-henriksen","<div>Show how the UI can build, almost without styling. So coding convention and clean code. Ensure everyone uderstands snapshot testing.<br /><strong>Hands-on:</strong> Create a simple form like Invite User</div>"
using-ui-toolkit-and-frontend-development-3,Using UI Toolkit and frontend development,templafy-aps,Room 6,"Platform, Email Signature",100,2019-08-07 09:00,2019-08-07 10:15,"dan-antal, morten-henriksen","<div>Show how the UI can build, almost without styling. So coding convention and clean code. Ensure everyone uderstands snapshot testing.<br /><strong>Hands-on:</strong> Create a simple form like Invite User</div>"`